std = "roblox"

[rules]
parse_error = "allow"
undefined_variable = "allow"
unused_variable = "allow"
shadowing = "allow"
empty_if = "allow"
incorrect_standard_library_use = "warn"
parenthese_conditions = "allow"